config/routes.rb
Rails.application.routes.draw do
  resources :gossips
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :gossip
end

app/models/gossip.rb
class Gossip < ApplicationRecord
	belongs_to :user, optional: true
	has_and_belongs_to_many :tags
	has_many :comments
	has_many :likes
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :gossip, optional: true
	
end

app/models/tag.rb
class Tag < ApplicationRecord
	belongs_to :gossip
end

app/models/user.rb
class User < ApplicationRecord
	has_many :comments
	has_many :likes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comment_controller.rb
class CommentController < ApplicationController
	@comment = Comment.all
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  before_action :set_gossip, only: [:show, :edit, :update, :destroy]

  # GET /gossips
  # GET /gossips.json
  def index
    @gossips = Gossip.all
  end

  # GET /gossips/1
  # GET /gossips/1.json
  def show
  end

  # GET /gossips/new
  def new
    @gossip = Gossip.new
  end

  # GET /gossips/1/edit
  def edit
  end

  # POST /gossips
  # POST /gossips.json
  def create
    @gossip = Gossip.new(gossip_params)

    respond_to do |format|
      if @gossip.save
        format.html { redirect_to @gossip, notice: 'Gossip was successfully created.' }
        format.json { render :show, status: :created, location: @gossip }
      else
        format.html { render :new }
        format.json { render json: @gossip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gossips/1
  # PATCH/PUT /gossips/1.json
  def update
    respond_to do |format|
      if @gossip.update(gossip_params)
        format.html { redirect_to @gossip, notice: 'Gossip was successfully updated.' }
        format.json { render :show, status: :ok, location: @gossip }
      else
        format.html { render :edit }
        format.json { render json: @gossip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gossips/1
  # DELETE /gossips/1.json
  def destroy
    @gossip.destroy
    respond_to do |format|
      format.html { redirect_to gossips_url, notice: 'Gossip was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gossip
      @gossip = Gossip.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gossip_params
      params.require(:gossip).permit(:title, :author, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/views/gossips/_form.html.erb
<%= form_with(model: gossip, local: true) do |form| %>
  <% if gossip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gossip.errors.count, "error") %> prohibited this gossip from being saved:</h2>

      <ul>
      <% gossip.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/gossips/edit.html.erb
<h1>Editing Gossip</h1>

<%= render 'form', gossip: @gossip %>

<%= link_to 'Show', @gossip %> |
<%= link_to 'Back', gossips_path %>

app/views/gossips/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Gossips</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Content</th>
      <th>Nb de commentaire</th>
      <th>Likes</th>
      <th>Tags</th>
      <th colspan="6"></th>
    </tr>
  </thead>

  <tbody>
    <% @gossips.each do |gossip| %>
      <tr>
        <td><%= gossip.title %></td>
        <td><%= gossip.author %></td>
        <td><%= gossip.content %></td>
        <td><%=Gossip.joins(:comments, :likes).count%></td>
        <td><%=@comment%></td>
        <td><%=Gossip%></td>
        <td><%= link_to 'Show', gossip %></td>
        <td><%= link_to 'Edit', edit_gossip_path(gossip) %></td>
        <td><%= link_to 'Destroy', gossip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gossip', new_gossip_path %>

app/views/gossips/new.html.erb
<h1>New Gossip</h1>

<%= render 'form', gossip: @gossip %>

<%= link_to 'Back', gossips_path %>

app/views/gossips/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @gossip.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @gossip.author %>
</p>

<p>
  <strong>Content:</strong>
  <%= @gossip.content %>
</p>

<p>
  <strong>Comentaire:</strong>
  <%=@comment.content  %>
</p>

<%= link_to 'Edit', edit_gossip_path(@gossip) %> |
<%= link_to 'Back', gossips_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GoGossips</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>